version: '3.8'

services:
  twitch_bot:
    image: <DEIN_DOCKERHUB_USERNAME>/l8temod:latest
    container_name: l8temod_bot
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "9999:5000"
