version: '3.8'

services:
  twitch_bot:
    image: <DEIN_DOCKERHUB_USERNAME>/l8temod:latest
    container_name: l8temod_bot
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - "9999:5000"
    environment:
      - TWITCH_CLIENT_ID=
      - TWITCH_CLIENT_SECRET=
      - GEMINI_API_KEY=
      - BOT_NICK=L8teBot
      - CHANNEL_NAME=
      - REDIRECT_URI=http://localhost:9999/callback
